### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by kmksrzw** [kmksrzw/furima-38586#25]
URL
https://furima-38586.onrender.com
Basic認証
ID admin
パスワード　2222  
出品者用
メールアドレス　test001@ne.jp
パスワード　　test1111
購入者用
メールアドレス   test002@ne.jp
パスワード      test2222

**Comment by wakazo228** [comment]
@kmksrzw さん、ご提出ありがとうございます！お待たせいたしました。
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

#### `商品一覧表示画面`
- [x] **左上から、出品された日時が新しい順に表示されること**
左上から、出品された日時が古い順に表示されています。新しい順に表示されるように修正してください。

#### `商品詳細画面`
- [x]  **商品出品時に登録した情報（商品名・商品画像・販売価格・配送料負担・商品説明・出品者名・カテゴリー・商品の状態・発送元の地域・発送日の目安）が、見本アプリと同様の形で出力されること**
商品詳細画面に「商品名」が表示されていません。表示されるよう修正してください。
![スクリーンショット 2023-03-28 17 49 08](https://user-images.githubusercontent.com/53425908/228183204-6de2cfad-9523-4cef-b851-325c8a929f00.png)

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！

※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by kmksrzw** [comment]
動作確認有難うございました。
ご指摘の箇所を修正いたしました。

**Comment by motomuun** [comment]
@kmksrzw さん、ご提出ありがとうございます‼︎
正常に動作することが確認できました！　LGTMです✨　
おめでとうございます🎉
着実に技術力が身につき、実用的なアプリになってきてますね（^^）


**※確認したのは必須機能のみです。追加実装した機能については確認しておりません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるか、再度ご自身でご確認をお願い致します。**
**※Github上の最終課題の履歴はここまで頑張ってきた証です。削除せず大切に保管するようにしましょう。**

![lgtm_01](https://user-images.githubusercontent.com/65059944/228394305-1641be3b-31ae-4002-a2e8-70d5b9dd761a.png)
